### ISSUE TITLE
Creditmemo: Qty is not back in stock

### ISSUE THREAD

**Issue by biwac** [wallee-payment/magento-2#1]
Even if the Magento Configuration "Stores > Configuration > Catalog > Inventory > Product Stock Options > Automatically Return Credit Memo Item to Stock" is set to "yes", the product qty is not back in stock after a refund in Wallee is created.

Config path: cataloginventory/item_options/auto_return

The disired behaviour can be achieved with the following method:
`$creditmemoItem->setBackToStock(true);`

To get the config value as described above we could get it like this:
`\Magento\CatalogInventory\Api\StockConfigurationInterface::isAutoReturnEnabled($store);`

My best guess would be to update the following class:
Wallee\Payment\Model\Webhook\Listener\Refund\SuccessfulCommand

```
/**
* @var Magento\CatalogInventory\Api\StockConfigurationInterface
**/
protected $stockConfiguration;

public function __construct(
   Magento\CatalogInventory\Api\StockConfigurationInterface $stockConfiguration,
   ...
){
   ...
   $this->stockConfiguration = $stockConfiguration;
}

private function registerRefund(...){
   ...
   
   foreach ($creditmemo->getAllItems() as $creditmemoItem) {
       $creditmemoItem->setBackToStock($this->stockConfiguration->isAutoReturnEnabled());
   }
   
   $this->creditmemoManagement->refund($creditmemo);
}

```

**Comment by schurter-wallee** [comment]
Implemented in version 1.0.60.
