### ISSUE TITLE
Unable to download deliveryslip from magento backend

### ISSUE THREAD

**Issue by philippeaellig** [wallee-payment/magento-2#11]
since 1.3.9 the invoice download link works again. but now, the deliverslip download link is not working anymore. on clicking on the link, i get a 404 error.

**Comment by theodorspringwallee** [comment]
Dear [philippeaellig](https://github.com/philippeaellig)

Can you tell us, under which payment method you see the deliverslip download link of wallee?

On our test-system we only recognize the normal "invoice" link:
![Bildschirm­foto 2022-11-03 um 15 41 14](https://user-images.githubusercontent.com/85299706/199751959-5329efc6-eda0-4e6f-a46d-d3f64555f97c.png)

If possible, please also provide a screenshot.

Best regards

**Comment by philippeaellig** [comment]
![image](https://user-images.githubusercontent.com/2021719/199773260-624d9bc0-9c60-4ca0-b7a4-1bd3fbb80666.png)
in the shippment. see screenshot.

**Comment by theodorspringwallee** [comment]
Dear [philippeaellig](https://github.com/philippeaellig)

Thank you for your answer.

We will investigate on this.

Best regards

**Comment by philippeaellig** [comment]
status?

**Comment by philippeaellig** [comment]
status?

**Comment by andrewrowanwallee** [comment]
this was fixed
