### ISSUE TITLE
de_CH translation missing

### ISSUE THREAD

**Issue by philippeaellig** [wallee-payment/magento-2#12]
i am missing the de_CH translation file. Many of our setup are in de_CH, because the translations are different to de_DE (ss/ß and more).

**Comment by theodorspringwallee** [comment]
Dear [philippeaellig](https://github.com/philippeaellig)

We added this as as feature request. 

Best regards

**Comment by philippeaellig** [comment]
status?

**Comment by philippeaellig** [comment]
status?

**Comment by andrewrowanwallee** [comment]
@philippeaellig de_ch was added in 2.1.20
