### ISSUE TITLE
State Suspected Fraud

### ISSUE THREAD

**Issue by FloWord** [wallee-payment/magento-2#13]
We have updated wallee/sdk (2.1.6 => 3.1.2) and wallee/magento-2 (1.1.8 => 1.3.11) module.
Now we get the status "Suspected Fraud" for every order in testmode.

![image](https://user-images.githubusercontent.com/21309911/201298659-00c21287-3bad-4fba-8a5e-4f67fa0c1bd6.png)
![image](https://user-images.githubusercontent.com/21309911/201298713-9f79c2d8-07e9-45d6-91ad-de7467e23a3d.png)

Is that normal or a issue in testmode?

**Comment by theodorspringwallee** [comment]
Dear [FloWord](https://github.com/FloWord)

This is a BUG. Our developers are aware of this and will fix this ASAP.

Best regards
