### ISSUE TITLE
Wallee payment methods not available in admin order creation process

### ISSUE THREAD

**Issue by norgeindian** [wallee-payment/magento-2#14]
When you try to create orders in the admin area, no Wallee payment methods are shown there.
The reason for that is the following:

- In `Wallee\Payment\Model\Service\AbstractLineItemService::convertLineItems()`, the following method is called as soon as items are added to the quote:
- ` $giftCardaccount = $this->giftCardAccountManagement->getListByQuoteId($entity->get()['entity_id']);`
- In this function, it is firstly checked, if the current quote is already active (`$quote = $this->quoteRepository->getActive($cartId);
`).
- This always returns throws the following error: `Magento\Framework\Exception\NoSuchEntityException: No such entity with cartId =XXX`, as the quote is not active yet at this point, as you can easily reproduce on a clean Magento instance.

Please be so kind and have a look at this issue.
I tested with `wallee/magento-2 1.3.14` on a clean Magento `2.4.5-p1`.

**Comment by theodorspringwallee** [comment]
Dear [norgeindian](https://github.com/norgeindian)

We will check this on our side.

Thank you very much for your input.

Best regards

**Comment by norgeindian** [comment]
@theodorspringwallee , thanks for the reply and a good start in 2023.
Did you already find time to reproduce this issue on your side? Do you need more information / details from my side?
As we want to go live end of January and definitely need this feature, it would be awesome if you could handle this issue with the highest possible priority.
Thanks and best regards

**Comment by theodorspringwallee** [comment]
Dear [norgeindian](https://github.com/norgeindian)

Unfortunately, we currently don't support MOTO transactions with the Magento 2 Wallee plugin.

Nevertheless, I have reopened this ticket as a feature-request.

I assume we can give you a final answer to this within this month.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [norgeindian](https://github.com/norgeindian)

I've got a quick response from our product owner.

Unfortunately, this feature we will not implement in the next time.

Best regards

**Comment by norgeindian** [comment]
@theodorspringwallee , that is pretty unpleasant, as we specifically chose Wallee as payment provider because your documentation states pretty clearly (see https://plugin-documentation.wallee.com/wallee-payment/magento-2/1.3.14/docs/en/documentation.html#:~:text=Backend%20Orders,the%20payment%20details.) that you support this kind of process.
How comes, that you changed your mind regarding this now?
I have to talk to our customer, but for them this feature is definitely needed.

**Comment by theodorspringwallee** [comment]
Dear [norgeindian](https://github.com/norgeindian)

Of course, you're right. I forwarded this to our product owner. 

Sorry for these circumstances. I hope you will get positive feedback now.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [norgeindian](https://github.com/norgeindian)

In our test systems with the same Magento and Wallee Version, we can't reproduce our issue: 
https://user-images.githubusercontent.com/85299706/210763475-5e1a4541-9fae-475a-a722-89d2a04dab91.mp4
We also tested this in addition with an applied coupon.

If you think we did something wrong in our reproduction, please let us know.

Please, can you ensure on the wallee plugin menu, that you also have the same SDK version?
![image](https://user-images.githubusercontent.com/85299706/210764170-600eb41b-40da-482d-a64e-ec375dcd7443.png)

Since we can't confirm this BUG, please can you create a support ticket by contacting info@wallee.com.
You can mention there this Git Issue and ask for me (Theodor Spring).

Best regards

**Comment by norgeindian** [comment]
@theodorspringwallee, thanks for checking.
Sorry, I fear I forgot to write down, that we are using the enterprise edition of Magento `2.4.5-p1`.
I just found your wrapper `vendor/wallee/magento-2/Model/Service/Quote/GiftCardAccountWrapper.php`, which uses an empty class in case of the community edition. So this makes sense, that the issue does not appear on this version. Could you please test again with the enterprise edition and let me know if you can reproduce it there?
Thanks and best regards

**Comment by theodorspringwallee** [comment]
Dear [norgeindian](https://github.com/norgeindian)

Thanks for the precision. We will check this within the plugins team.

Best regards

**Comment by norgeindian** [comment]
This is fixed in version 1.3.16, so this ticket can be closed.
