### ISSUE TITLE
The line item total amount of the provided items (126.18) is greater than the total amount of the original items (111.93).

### ISSUE THREAD

**Issue by FloWord** [wallee-payment/magento-2#15]
Hello Team,
with the new Release 1.3.14 we found out, that we can`t raise the total amount after order!

`The line item total amount of the provided items (126.18) is greater than the total amount of the original items (111.93).`

With the payment method invoice from mf group/power pay, however, we have to be able to increase or decrease the amount depending on the order.
Why is there this new restriction and can it be lifted again?
Thanks for any help and support.

**Comment by theodorspringwallee** [comment]
Dear [FloWord](https://github.com/FloWord)

Thank you for your input.

We will check this on our side.

In the meanwhile, did you already check if the issue will be fixed on your side when turning on/off the "Enforce consitency" option in the wallee plugin menu?
![image](https://user-images.githubusercontent.com/85299706/208474723-09789548-080c-4cc7-86a9-aaa1ba10e139.png)
That has influences on how the sum will be calculated.

Thank you for your feedback.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [FloWord](https://github.com/FloWord)

I assume there was a misunderstanding.

You probably meant the adjustments options within the portal, right?
![image](https://user-images.githubusercontent.com/85299706/208480973-2ab574ee-335b-44ae-b46b-a4faac4b322f.png)

I will forward this to our portal team. 

Best regards

**Comment by swiss-wiederkehr** [comment]
Dear @theodorspringwallee 
i disabled the feature "Enforce..." but i got the same message:
![image](https://user-images.githubusercontent.com/21309911/208662174-5ac70d37-1f0a-480a-859a-328db28d375c.png)
It is not in the portal, it comes in the backend of magento 2 after shipping methode, i think there is a new policy rule of wallee?

Best regards

**Comment by theodorspringwallee** [comment]
Dear [FloWord](https://github.com/FloWord)

It's actually the same function, which is called. In the Magento 2 backend (over the Wallee API) or in the wallee portal directly on the transaction.

According to our portal developers it's up to the payment processor, where the increasing of the authorized amount is allowed. For Powerpay it's not allowed to increase the value of authorized amounts.

If you think this is wrong and could be implemented on our side, please get in touch with Powerpay to clarify.

For further communication we appreciate, that you create a support ticket, by writing to info@wallee.com

This git issue will be closed.

Best regards
