### ISSUE TITLE
"Current customer does not have an active cart" warning when paying via invoice

### ISSUE THREAD

**Issue by norgeindian** [wallee-payment/magento-2#19]
When paying via invoice as a logged in customer, one gets the following error message displayed in the checkout, as soon as one purchases:
"Current customer does not have an active cart"

The purchase can be done anyway, but the error message still appears on the checkout page,

As far as I could see in my first tests, this happens in `\Wallee\Payment\Controller\Checkout\RestoreCart` where the quote is restored at a point, where it does not exist anymore. The error itself is thrown in `\Magento\Quote\Model\Webapi\ParamOverriderCartId::getOverriddenValue`.

I tried to reproduce the issue on the wallee testing page, but there, invoice is currently not supported.
So if someone could change that and activate payment via invoice, I would be happy to test again there and provide further information about this error.

**Comment by theodorspringwallee** [comment]
Dear [norgeindian](https://github.com/norgeindian)

Let's continue this conversation in one of our tickets.

I've written you already.

Best regards
