### ISSUE TITLE
Incomplete Gift Card Support (Adobe Commerce)

### ISSUE THREAD

**Issue by sprankhub** [wallee-payment/magento-2#20]
1. PHP 8.1
2. Adobe Commerce 2.4.5-p1
3. `wallee/magento-2` 1.3.16
4. enable `wallee_payment/line_items/enforce_consistency`
5. add a product to the cart
6. in the cart, add a gift card (not a coupon code from the sales rules, but a real gift card!)
7. go to checkout and enter all data
8. try to order

Expected: The order is saved, you will be redirected to the success page.
Actual: You will get an exception ("The line item total amount of X does not match the expected amount of Y.).

**Comment by theodorspringwallee** [comment]
Dear [sprankhub](https://github.com/sprankhub)

Are you talking about the Gift Card you can choose in the catalog?
![image](https://user-images.githubusercontent.com/85299706/215496392-96ef490d-e38d-4f22-83c4-5378692eab52.png)

If yes, please can can you tell us, if you are using an extension for this? 

In our M2 showcase (https://magento-2.showcase-wallee.com/) we do not have this Gift Card option.

Thank you for providing the reproduction steps for this.

Best regards

**Comment by sprankhub** [comment]
This is a Commerce feature. See Marketing > Gift Card Accounts:

![image](https://user-images.githubusercontent.com/930199/215497821-729794ca-6920-422c-b45f-3cd23b7fbf00.png)

**Comment by theodorspringwallee** [comment]
Dear [sprankhub](https://github.com/sprankhub)

Those Gift Cards seems to be an Adobe Commerce exclusive feature: https://experienceleague.adobe.com/docs/commerce-admin/stores-sales/point-of-purchase/gift-cards/product-gift-card-workflow.html?lang=en

Currently, we only have "normal" Magento 2 test instances.

We don't have these features there:
![image](https://user-images.githubusercontent.com/85299706/215499850-776578dc-62c9-42ba-a5d7-3e3e967c0343.png)

I will check with our plugin team, how to continue there.

Best regards
