### ISSUE TITLE
GDPR Mode setting is irrelevant

### ISSUE THREAD

**Issue by FloWord** [wallee-payment/magento-2#23]
We use Magento `2.4.3` and updated Wallee from `1.3.18` to `1.3.20`. The GDPR mode enable or disable is on our system irrelevant, on both settings - the fields for powepay invoice are coming.

![image](https://user-images.githubusercontent.com/21309911/223741020-e8fcd461-0f3a-4c0e-ad4f-c84e38515ccd.png)

**Comment by theodorspringwallee** [comment]
Dear [FloWord](https://github.com/FloWord)

We checked this on our showcase (https://magento-2.showcase-wallee.com) and are not able to reproduce this (see video):

https://user-images.githubusercontent.com/85299706/223751347-ebd380a7-a8ca-4bc1-87b2-22ce4326b690.mp4

Please, can you get in touch with us over info@wallee.com, that we can look at your issue?

Best regards

**Comment by swiss-wiederkehr** [comment]
Hi @theodorspringwallee i think there is indeed a bug here and it can be reproduced on a test system as well.

**Comment by theodorspringwallee** [comment]
Dear [FloWord](https://github.com/FloWord), we can confirm this. Our developers will check and fix this.

Best regards

**Comment by swiss-wiederkehr** [comment]
Problem is fixed in Version 1.3.23
