### ISSUE TITLE
The delivery and billing address must be identical.

### ISSUE THREAD

**Issue by FloWord** [wallee-payment/magento-2#24]
We use Wallee `1.3.18` and have a problem with the `Powerpay` payment method with a logged-in customer.

`The delivery and billing address must be identical.`
![image](https://user-images.githubusercontent.com/21309911/225283590-9555ac2a-0ea8-4ad3-8649-20523a558b18.png)

The delivery and billing address are identical in the shop.
I can reproduce it with the customer account.

**Comment by theodorspringwallee** [comment]
Dear [FloWord](https://github.com/FloWord)

We can't reproduce this in our showcase (https://magento-2.showcase-wallee.com):

https://user-images.githubusercontent.com/85299706/225315871-b40ce1d0-16d7-42f7-aebd-a8f3b6cfe60c.mp4



Can you check please again with our newest plugin version?

Previously, I also was not able to reproduce your other mentioned issue (https://github.com/wallee-payment/magento-2/issues/23), so this also could be fixed now.

Best regards

**Comment by swiss-wiederkehr** [comment]
Hello @theodorspringwallee i can reproduce this issue for one customer, not for all others.

**Comment by theodorspringwallee** [comment]
Dear [FloWord](https://github.com/FloWord)

In this case, please create a ticket by writing to info@wallee.com

Best regards
