### ISSUE TITLE
Postpone Invoice Creation

### ISSUE THREAD

**Issue by sprankhub** [wallee-payment/magento-2#25]
We would like to postpone the invoice creation. Currently, the Magento invoice is created directly after the order is created and the Wallee invoice is also sent at the same time. We would like to do this only when the order is shipped.

The Magento invoice seems to be created in `\Wallee\Payment\Observer\SubmitQuote::execute`. This is also where the transaction is confirmed. I guess this is also the place, where Wallee sends the invoice? Could we just disable that observer and execute pretty much the same code on shipment creation? Is there any issue with not confirming the transaction for a few days? This would e.g. happen if the client orders Friday evening, and we only ship the order on Monday.

**Comment by theodorspringwallee** [comment]
Dear [sprankhub](https://github.com/sprankhub)

I will forward your question to our developers.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [sprankhub](https://github.com/sprankhub)

According to our developers, the invoice is required for the transaction process:
> The invoice is used to track the transaction status. This is why we have created right away.

I hope this answers your question.

Best regards

**Comment by sprankhub** [comment]
@theodorspringwallee, thanks for the answer. However, I do not care too much why you implemented it that way. The questions is: Is there any issue on your side if we change it as I described above?

**Comment by theodorspringwallee** [comment]
Dear [sprankhub](https://github.com/sprankhub)

I will ask our developers again.

Would it also be an option to set the payments into the deferred mode (e.g. each Friday), that would mean, that the wallee transaction status does not switch automatically to fulfil. 

Would that match with your use case?

Best regards

**Comment by sprankhub** [comment]
How does deferred mode work exactly? However, I fear it will not work for us: We want to create the invoice when we ship the order, so we need to be able to trigger that manually.

**Comment by theodorspringwallee** [comment]
Dear [sprankhub](https://github.com/sprankhub)

The deferred mode you can activate on your specific connector (change with the "edit" button the value "immediate" to "deferred"):
![grafik](https://github.com/wallee-payment/magento-2/assets/85299706/91698062-0f00-4f22-abc1-6e04e23c2124)

That means, the transaction status will only reach the "authorized" state. To reach further transaction states till to the "fulfilled" state, you need then to capture those transactions manually.

For example, if you want, that the customer do not receive a wallee mail on the "authorized" state (when the transaction isn't booked) you can disable the "authorized"-mail within the wallee space settings:
![grafik](https://github.com/wallee-payment/magento-2/assets/85299706/2a647d79-21e1-44e8-bb73-eb2a13d33758)

And on the next Monday, you can capture the transactions of Friday.

Does this help you?

Best regards

**Comment by sprankhub** [comment]
That could be interesting, indeed. Thanks! I will check if that works for us.

**Comment by theodorspringwallee** [comment]
Dear [sprankhub](https://github.com/sprankhub)

Did not hear from you since a while. I'll close this git issue now. 

Feel free to re-ask, when you have additional questions to this topic.

Best regards
