### ISSUE TITLE
Error in Checkout with virtual products such as a print@home giftcards

### ISSUE THREAD

**Issue by FloWord** [wallee-payment/magento-2#26]
There is an issue with the "Mageplaza" or all other **virtual GiftCards** products, specifically with version `1.3.23` with `1.3.18` it works. When trying to use print@home gift cards, which are **virtual products**, users are redirected to a Wallee page with an error message.

Steps to reproduce:

Install Mageplaza GiftCards
Create a print@home gift card product.
Attempt to purchase the gift card and choose print@home.
Observe that the user is redirected to a Wallee page with an error message.

Expected result:

Users should be able to purchase and receive print@home gift cards without being redirected to a Wallee page with an error message.

Workaround:

As a temporary workaround, downgrade to version `1.3.18`

**Comment by theodorspringwallee** [comment]
Dear [FloWord](https://github.com/FloWord)

I will forward your request to our developers. But since we do not officially support "Mageplaza" or those other virtual GiftCards it will probably be a feature request.

To make it easier for our developers, please can you provide us some screenshots or a reproduction video, where you create those GiftCards (in which menus and how).

Many thanks for your answer.

Best regards

**Comment by swiss-wiederkehr** [comment]
Hello @theodorspringwallee 

here some screenshot from checkout:
![image](https://user-images.githubusercontent.com/21309911/235877358-65b23b18-a915-4096-a430-2d88a1f3deb1.png)
![image](https://user-images.githubusercontent.com/21309911/235877522-29269abb-2eb9-4647-9f77-bffb338f5b06.png)

thank you
Best regards

**Comment by theodorspringwallee** [comment]
Dear [FloWord](https://github.com/FloWord)

Thanks for your screenshots.

Please can you also provide us some screenshots, where and how you created those not working coupons in your shop backend?

Many thanks for your answer.

Best regards

**Comment by swiss-wiederkehr** [comment]
Hi @theodorspringwallee 
you need mageplaza giftcard extension, without, can you try to create a simple virtual product and buy it?

**Comment by theodorspringwallee** [comment]
Dear [FloWord](https://github.com/FloWord)

We will discuss this within the plugin developer team.

So you are using this chargeable plugin here? https://www.mageplaza.com/magento-2-gift-card-extension/ 

Best regards

**Comment by swiss-wiederkehr** [comment]
@theodorspringwallee yes
