### ISSUE TITLE
Provide Value Date In Magento

### ISSUE THREAD

**Issue by sprankhub** [wallee-payment/magento-2#27]
https://support.wallee.com/hc/en-us/articles/360019053399-How-to-get-bank-transactions-via-the-API- talks about integrating Magento 2 / Wallee with an ERP system. For invoice payments (and others as well), Wallee already transfers some data from Wallee to Magento:

![image](https://github.com/wallee-payment/magento-2/assets/930199/644292e7-918e-4a19-814a-a4d5de6ff8b7)

However, in order to properly integrate Magento with the ERP system, we need to also have the value date of the respective [bank transaction](https://app-wallee.com/en-us/doc/api/model/bank-transaction). Would you be able to also transfer the value date of the bank transaction from Wallee to Magento as well? We could of course talk to the [Wallee API](https://app-wallee.com/en-us/doc/api/web-service#bank-transaction-service) ourselves and get it, but I would prefer the plugin doing this by default :)

Background: We import CAMT files from the bank into Wallee to mark invoices as paid. However, a common case is that the payment is done yesterday, but the respective CAMT file is only imported today. Then, it looks like the payment has been done today, even though it has been done yesterday already. This leads to a date mismatch, so that we get issues on the ERP-side.

**Comment by theodorspringwallee** [comment]
Dear [sprankhub](https://github.com/sprankhub)

I forwarded your feature request proposal to our developers.

Best regards

**Comment by sprankhub** [comment]
Thanks, @theodorspringwallee! Did you get any feedback already?

**Comment by theodorspringwallee** [comment]
Dear [sprankhub](https://github.com/sprankhub)

I assume it will take another 1-3 weeks, till our product owners have a decision here.

Best regards

**Comment by sprankhub** [comment]
Any news, @theodorspringwallee? Thanks!

**Comment by sprankhub** [comment]
Any news by now, @theodorspringwallee? Thanks!

**Comment by theodorspringwallee** [comment]
Dear [sprankhub](https://github.com/sprankhub)

Unfortunately, our product owners couldn't make a decision till yet.

We will let you know as soon a decision will be there.

Best regards

**Comment by sprankhub** [comment]
Even though I think it would be a good addition, we found another solution and don't necessarily need this any more. So I will stop bugging you with this ;-)
