### ISSUE TITLE
PHP 8.2 Support

### ISSUE THREAD

**Issue by sprankhub** [wallee-payment/magento-2#28]
Magento 2.4.6 supports PHP 8.2. Hence, this module should also support PHP 8.2.

**Comment by theodorspringwallee** [comment]
Dear [sprankhub](https://github.com/sprankhub)

I forwarded your feature request to our developers.

Best regards

**Comment by sprankhub** [comment]
Is PHP 8.2 supported by now, @theodorspringwallee?

**Comment by theodorspringwallee** [comment]
Dear [sprankhub](https://github.com/sprankhub)

Currently, the plugin is tested against up to PHP 8.1.16

We have a pending feature request on our side to implement the PHP 8.2 compatibility.

I re-asked when we will start on this.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [sprankhub](https://github.com/sprankhub)

After asking again, our plugin team can confirm that we are already compatible up to PHP 8.2.8 and we will add this to the next release documentation as well.

Best regards
