### ISSUE TITLE
FullfillCommand leaves order status as processing_wallee

### ISSUE THREAD

**Issue by jhruehl-DEN** [wallee-payment/magento-2#29]
In wallee/magento-2/Model/Webhook/Listener/Transaction/FulfillCommand.php the order status is set to "processing", if the order can be fullfilled, but given that the processing_wallee state is set as default value for the processing statuses (in wallee/magento-2/Setup/Patch/Data/UpdateStatusStateData.php), it leaves the orders in the "Hold delivery" status, because updating the oder status via "$order->addStatusToHistory(true, \__('The order can be fulfilled now.'));" sets the default order status value for the last set order state, which your update script ensures to be processing_wallee now.

The basic mistake the developers have made is mingling with the default magento order processes by setting another default state for the processing status. This should be addressed and I guess it already caused a lot of customers quite some headache, because the Magento 2 order flow relies on the order statuses to have certain values like "processing" to continue and not on "processing_wallee".

As the processing_wallee status label "Hold Delivery" suggests, it should not be shown when "The order can be fulfilled now.".

I'm going to check myself now, if I can simply correct that mistake by resetting the order state "processing" as default for the order status "processing".

**Comment by jhruehl-DEN** [comment]
As expected: Resetting the order state "processing" as default for the order status "processing" instead of "processing_wallee" fixed the issue and the order status is correctly set to "Processing" instead of "Hold Delivery" when wallee calls the webhook to set the order as fullfillable.

**Comment by jhruehl-DEN** [comment]
Not sure about the intention in vendor/wallee/magento-2/Setup/Patch/Data/AddSetupData.php class either. 
![grafik](https://github.com/wallee-payment/magento-2/assets/79449853/b799303b-91ec-496f-8227-cd90d3dafd61)

=>
![grafik](https://github.com/wallee-payment/magento-2/assets/79449853/22c40714-2a11-4939-be9e-b5727d34c890)

=>
![grafik](https://github.com/wallee-payment/magento-2/assets/79449853/ce0f7ddd-c120-4fb7-b215-54321286278a)


But it seems that is another cause for the processing_wallee status to become the default for the processing state.

**Comment by theodorspringwallee** [comment]
Dear [jhruehl-DEN](https://github.com/jhruehl-DEN)

Thanks for your input. We will double-check our product behavior and will give you feedback.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [jhruehl-DEN](https://github.com/jhruehl-DEN)

The "processing_wallee" is equals the "HOLD DELIVERY" state in Magento. 
This is a business decision for our plugin on our side.

If you want to change the "Processing" Magento state label on the M2 order, you simply can rename the label:
![grafik](https://github.com/wallee-payment/magento-2/assets/85299706/49507321-95e1-421f-941e-9b268cdf2518)
![grafik](https://github.com/wallee-payment/magento-2/assets/85299706/4b5db41b-95b7-4691-b600-c0ac34a31eb5)

Best regards

**Comment by jhruehl-DEN** [comment]
@theodorspringwallee It's not at all about the order **status** processing_wallee, but about your extension making it the default for the **order state** "processing". That way the order stays on "Hold Delivery" even when the webhook is called to set the order to "The order can be fulfilled now." or send that the payment has been fullfilled. 

Because of this line:
https://github.com/wallee-payment/magento-2/blob/c8fc5a2411e7b36f5382aa3c126c08c0e7f48d82/Model/Webhook/Listener/Transaction/FulfillCommand.php#L61C13-L61C86

Given you set true in here: $order->addStatusToHistory(true, \__('The order can be fulfilled now.'));

This leads to the default status to be used for the status "processing", which by your update script is set to be "processing_wallee".

In pictures:
With your extension changing "processing_wallee" as the default status of the order state "processing".
![grafik](https://github.com/wallee-payment/magento-2/assets/79449853/310074f1-7c45-483e-8951-bb6cc3b09b6d)

With my fix to set the order status "processing" back as default for the order state "processing"
![grafik](https://github.com/wallee-payment/magento-2/assets/79449853/285d419d-5d98-4363-8b61-62f4b31f584f)

Click through your code in a Magento2 vanilla project yourself under the premise of your default-value changes.

The question is, if it was even your intention to adjust the default-value, because the use in the given upgrade script is wrong, because you serve the string "processing" as the supposedly boolean value for "isDefault" (second argument in assignState function call) here.
https://github.com/wallee-payment/magento-2/blob/c8fc5a2411e7b36f5382aa3c126c08c0e7f48d82/Setup/Patch/Data/AddSetupDataState.php#L42

**Comment by jhruehl-DEN** [comment]
![grafik](https://github.com/wallee-payment/magento-2/assets/79449853/e52c70ed-9d24-4bb2-88e8-72e9bee8cf50)

**Comment by philippeaellig** [comment]
status?

**Comment by mmezhensky** [comment]
@theodorspringwallee, @jhruehl-DEN
Do you have some updates here? I have the same problem. 
Please share a possible solution or progress here.

**Comment by philippeaellig** [comment]
status?

**Comment by andrewrowanwallee** [comment]
this was fixed
