### ISSUE TITLE
Change order from "processing" to "on hold" not working.

### ISSUE THREAD

**Issue by biwac** [wallee-payment/magento-2#3]
Hello there,

In our Magento 2.3 Setup we can't change orders from "processing" to "on hold" if the payment method is one provided by wallee.
Can you please look in this issue or explain us why this is not possible.

Also our customer would like to defer the dunning if an order is "on hold", is there any possibility to achive this?

Thanks

**Comment by schurter-wallee** [comment]
Hi, is this issue still open?

We tried to reproduce the described behavior but could not. Orders in state "processing" can easily be moved to "on hold". Are you sure, that the wallee plugin is causing this? Could you give us more detailed information?

Postponing the dunning for "on hold" orders is not possible, as this state cannot be mirrored to wallee.

**Comment by biwac** [comment]
Hello

We only tested this with the payment method "invoice" and we tought it would postponing the dunning process. 

I close this issue, because there is an other way to achive the desired behavior.
