### ISSUE TITLE
Performance Issue on Cart Page

### ISSUE THREAD

**Issue by sprankhub** [wallee-payment/magento-2#33]
On the cart page, you do some API calls, which can be slow. In our case, these calls slowed down the page by almost 700ms:

![image](https://github.com/wallee-payment/magento-2/assets/930199/ab903724-743e-4141-9b54-26cb58a4f5a7)

Could you please check and fix this?

**Comment by theodorspringwallee** [comment]
Dear [sprankhub](https://github.com/sprankhub)

The request time for the wallee API, by loading the iframe, is about 1.2 seconds (reproduced in our showcase):
![grafik](https://github.com/wallee-payment/magento-2/assets/85299706/5fde71e3-96f9-4e69-8bee-74f2c6bba342)

Overall in our showcase the loading time of a selected payment method (with Magento 2 code) is about 3.6 seconds:
![grafik](https://github.com/wallee-payment/magento-2/assets/85299706/35d629c8-1512-4ff0-951f-33321eba5104)

And the wallee API part is only a fraction of those 3.6 seconds. 

I assume this is a normal timeframe we can expect in online shops. 

The main part is probably about, how your checkout is programmed (other checkout integrations, your shop theme etc.).

Please let us know if we misunderstood your issue.

Best regards

**Comment by sprankhub** [comment]
You understood the issue correctly. 1.2 seconds of 3.6 seconds is 33 %, right? I consider this too much for any external integration / any payment method.

**Comment by theodorspringwallee** [comment]
Dear [sprankhub](https://github.com/sprankhub)

We did already some speed optimizations in the past. 

We will check how it can be possible to improve it more.

Best regards
