### ISSUE TITLE
Extract Graph QL Support

### ISSUE THREAD

**Issue by norgeindian** [wallee-payment/magento-2#34]
Since version 2.0.0, Magento_GraphQL is a fixed requirement.
It would be awesome if this requirement could be optional or the whole Graph QL functionality could be extracted into a separate module.

**Comment by theodorspringwallee** [comment]
Dear [norgeindian](https://github.com/norgeindian)

We will check your proposal with the developers and the product owner.

Thanks for your patience.

Best regards

**Comment by sprankhub** [comment]
@andrewrowanwallee, just closing issues without having them fixed and without adding any comment is not a nice action.

**Comment by andrewrowanwallee** [comment]
@sprankhub this has been static for over a year, the prudent action is to close it

**Comment by sprankhub** [comment]
@andrewrowanwallee, just because you ignore the issue for over a year doesn't mean it's fixed :facepalm: 

This is just the issue, which is the most obvious, but it also applies to many others you just closed without fixing them.
