### ISSUE TITLE
Javascript error in Checkout with Version 2.1.17

### ISSUE THREAD

**Issue by FloWord** [wallee-payment/magento-2#39]
Hello Team

We updated wallee in our staging (Magento 2.4.7-p1) to version 2.1.17 and encountered error messages

![image](https://github.com/user-attachments/assets/06159bc3-8cf0-457c-b0ab-456acd1894b4)

Best regards

**Comment by BS-Wallee** [comment]
Dear FloWord,

thanks for your feedback. I have looked at this on our official DemoStore, but couldn't reproduce this behaviour/error like you did on your shop after trying to pay with multiple methods, see the screenshots attached.
You can test it yourself on our demostore here: https://magento-2.showcase-wallee.com/admin/
Usually such errors can happen if you are using a custom template or third party plugins that could influence the checkouts functions. As we are hooking into the workflow of the default Magento Environment, also third party templates can influence this behaviour. I recommend to check those first, and temporarily deactivating any of such as the easiest method of elimination. If you still can reproduce this on a fresh magento 2 installation without additional plugins/template active, I can of course take a closer look at it. In that case, I recommend that we handle this on our end. Please then reply to us over mail to info@wallee.com using the ticket number 311111 in the subject like this: "#311111". Also please include your space number and access to your shops backend there, so we can most efficiently take a look at it.

I hope this already helped so far. Looking forward in hearing if you were able to solve it.

Kind Regards
Wallee Support

**Comment by BS-Wallee** [comment]
Dear FloWord,

we haven't yet recevied feedback from you regard my last message. I will close the support case for now on our end, but you can just come back to this case at anytime by replying either here or directly on the support ticket itself via Mail.

Kind Regards
Wallee Support
