### ISSUE TITLE
Reorder with Payment Method "invoice" doesn't create an invoice in wallee

### ISSUE THREAD

**Issue by biwac** [wallee-payment/magento-2#4]
Hello there,

If our customer reorders an order with the payment method "invoice" for corrections the order is correctly created in magento. The order is also correclty synced to wallee but no invoice is created with the updated amounts and totals. Also no invoice PDF can be downloaded via Wallee.

Can you please take a look?

**Comment by schurter-wallee** [comment]
Hi again. For backend orders to work, you need to create a charge flow in Magento. Have you done this?
Or are you reordering in the frontend?
