### ISSUE TITLE
PHP8.1 compatibilty

### ISSUE THREAD

**Issue by s1mplex1337** [wallee-payment/magento-2#6]
With Magento 2.4.4 moving to PHP 8.1 wallee should be compatible. But it still has several errors as of yet.

E.g. during compilation:

PHP Fatal error:  During inheritance of ArrayAccess: Uncaught Exception: Deprecated Functionality: Return type of Wallee\Sdk\Model\PaymentMethodConfiguration::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/wallee/sdk/lib/Model/PaymentMethodConfiguration.php on line 754 in /vendor/magento/framework/App/ErrorHandler.php:61

**Comment by matmarchant** [comment]
It is also set to only allow php ~7.1.3||~7.2.0||~7.3.0||~7.4.0 in composer.json

**Comment by amokato** [comment]
When will the module be PHP 8 / Magento 2.4.5 compatible, is there a public roadmap for the module?

**Comment by theodorspringwallee** [comment]
Dear [s1mplex1337](https://github.com/s1mplex1337), [matmarchant](https://github.com/matmarchant)

Sorry for the late response.

In the meanwhile Magento 2.4.4 should be compatible with PHP 8.1.

Please install for this the newest plugin version: https://github.com/wallee-payment/magento-2/releases/tag/1.3.3

If you still have then problems there please contact our support: info@wallee.com
