### ISSUE TITLE
Incompatible CaptureCommand Class

### ISSUE THREAD

**Issue by amokato** [wallee-payment/magento-2#8]
We are on Magento 2.4.4 (CE) with the latest wallee (1.1.8) module installed. Although the "demo" payment seems to work. We are getting the following exception. We are running on PHP 7.4.

`2022-06-16T13:54:09.795128+00:00] main.CRITICAL: TypeError: Argument 1 passed to Magento\Sales\Model\Order::addRelatedObject() must be an instance of Magento\Framework\Model\AbstractModel, null given, called in /var/www/webroot/vendor/wallee/magento-2/Model/Webhook/Listener/TransactionInvoice/CaptureCommand.php on line 74 and defined in /var/www/webroot/vendor/magento/module-sales/Model/Order.php:2065`

It looks like that the model is not compatible to Magento 2.4.4

**Comment by MarksAfanasevics** [comment]
Now we have exception for Wallee webhooks also on live.
Wallee modules:
    "wallee/magento-2": "1.2.5",
    "wallee/sdk": "3.0.3"

Can we fix that, for example with this simple check?

```
diff --git a/vendor/wallee/magento-2/Model/Webhook/Listener/TransactionInvoice/CaptureCommand.php b/vendor/wallee/magento-2/Model/Webhook/Listener/TransactionInvoice/CaptureCommand.php
--- a/vendor/wallee/magento-2/Model/Webhook/Listener/TransactionInvoice/CaptureCommand.php	
+++ b/vendor/wallee/magento-2/Model/Webhook/Listener/TransactionInvoice/CaptureCommand.php	(date 1664285458302)
@@ -69,7 +69,7 @@
                 /** @var \Magento\Sales\Model\Order\Payment $payment */
                 $payment = $order->getPayment();
                 $payment->registerCaptureNotification($entity->getAmount());
-                if (! ($invoice instanceof InvoiceInterface) && ) {
+                if (! ($invoice instanceof InvoiceInterface) && !empty($payment->getCreatedInvoice())) {
                     $invoice = $payment->getCreatedInvoice();
                     $order->addRelatedObject($invoice);
                 } else {
```
Or this will brake further logic?

**Comment by theodorspringwallee** [comment]
Dear [amokato](https://github.com/amokato), [MarksAfanasevics](https://github.com/MarksAfanasevics)

Please can you update to the latest 1.3.3 wallee version: https://github.com/wallee-payment/magento-2/releases/tag/1.3.3

And check if the issue still appears? On our demo-shops with this version, we currently can't reproduce this.

If the issue still appears, please contact: info@wallee.com

**Comment by kamephis** [comment]
@theodorspringwallee the issue still appears. We two are now in contact and you can test it out on our stage soon.
